### ISSUE TITLE
haystack backend

### ISSUE THREAD

**Issue by jeromecc** [andreasofthings/feeds#4]
Hello!

I am fiddling with _feeds_, trying to get it up and running on my Linux laptop.

Which backend would you recommend for Haystack?

For now I just put this one in settings.py for testing, will it be enough to get __feeds__ up and running?

```
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
    },
}
```

Thanks!

**Comment by andreasofthings** [comment]
Hello!

Thanks for your feedback. `feeds` is likely in a `works for me` type of state and needs plenty of work done.

It' is not meant to be used standalone and needs to integrate with an existing django site.

To get it up, a SimpleEngine Backend should do, I use Woosh here, though.
